version: "3"
services:
  bootstrap:
    container_name: bootstrap
    build: "./bootstrap"
    image: localethereum/pyethapp-bootstrap
    ports:
      - 40002:30303
      - 40002:30303/udp
      - 41002:8545
    restart: always
    networks:
      back:
          ipv4_address: 172.18.250.2
  validator:
    container_name: validator
    build: "./validator"
    image: localethereum/pyethapp-validator
    environment:
      - BOOTSTRAP_NODE=enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@172.18.250.2:30303
    ports:
      - 40003:30303
      - 40003:30303/udp
      - 41003:8545
    restart: always
    networks:
      back:
          ipv4_address: 172.18.250.3
  miner:
    container_name: miner
    build: "./miner"
    image: localethereum/pyethapp-miner
    environment:
      - BOOTSTRAP_NODE=enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@172.18.250.2:30303
    ports:
      - 40004:30303
      - 40004:30303/udp
      - 41004:8545
    restart: always
    networks:
      back:
          ipv4_address: 172.18.250.4
networks:
  back:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.250.0/24
