filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /root/log/*
  exclude_lines: ["^.*?(INFO)", "^.*?(WARNING)", "^.*?(TRACE)", "^.*?(DEBUG)"]

# Filebeat modules
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
  reload.period: 10s

# Logstash
output.logstash:
  hosts: ["54.210.221.136:5000"]
